### ISSUE TITLE
How do I use this with Handlebars?

### ISSUE THREAD

**Issue by NetOpWibby** [ierhyna/hexo-reading-time#5]
Handlebars is similar to Swig, but I get errors when using this plugin.

**Comment by ierhyna** [comment]
Hi @NetOperatorWibby, I'm sorry, I'm not familiar with Handlebars. What kind of error do you get?

**Comment by NetOpWibby** [comment]
I'll paste the entire error I get in `console`:

```
Unhandled rejection Error: Parse error on line 47:
...</script>      {{ readingTime(page.con
---------------------^
Expecting 'ID', 'STRING', 'NUMBER', 'BOOLEAN', 'UNDEFINED', 'NULL', 'DATA', got 'INVALID'
    at Object.parseError (/Users/netopwibby/Desktop/Projects/NetOperatorWibby/theWebbBlog/node_modules/handlebars/dist/cjs/handlebars/compiler/parser.js:267:19)
    at Object.parse (/Users/netopwibby/Desktop/Projects/NetOperatorWibby/theWebbBlog/node_modules/handlebars/dist/cjs/handlebars/compiler/parser.js:336:30)
    at HandlebarsEnvironment.parse (/Users/netopwibby/Desktop/Projects/NetOperatorWibby/theWebbBlog/node_modules/handlebars/dist/cjs/handlebars/compiler/base.js:46:43)
    at compileInput (/Users/netopwibby/Desktop/Projects/NetOperatorWibby/theWebbBlog/node_modules/handlebars/dist/cjs/handlebars/compiler/compiler.js:514:19)
    at ret (/Users/netopwibby/Desktop/Projects/NetOperatorWibby/theWebbBlog/node_modules/handlebars/dist/cjs/handlebars/compiler/compiler.js:523:18)
    at Hexo.handlebarsRenderer (/Users/netopwibby/Desktop/Projects/NetOperatorWibby/theWebbBlog/node_modules/hexo-renderer-handlebars/index.js:34:10)
    at Hexo.tryCatcher (/Users/netopwibby/Desktop/Projects/NetOperatorWibby/theWebbBlog/node_modules/bluebird/js/release/util.js:16:23)
    at Hexo.<anonymous> (/Users/netopwibby/Desktop/Projects/NetOperatorWibby/theWebbBlog/node_modules/bluebird/js/release/method.js:15:34)
    at /Users/netopwibby/Desktop/Projects/NetOperatorWibby/theWebbBlog/node_modules/hexo/lib/hexo/render.js:61:21
    at tryCatcher (/Users/netopwibby/Desktop/Projects/NetOperatorWibby/theWebbBlog/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/Users/netopwibby/Desktop/Projects/NetOperatorWibby/theWebbBlog/node_modules/bluebird/js/release/promise.js:510:31)
    at Promise._settlePromise (/Users/netopwibby/Desktop/Projects/NetOperatorWibby/theWebbBlog/node_modules/bluebird/js/release/promise.js:567:18)
    at Promise._settlePromiseCtx (/Users/netopwibby/Desktop/Projects/NetOperatorWibby/theWebbBlog/node_modules/bluebird/js/release/promise.js:604:10)
    at Async._drainQueue (/Users/netopwibby/Desktop/Projects/NetOperatorWibby/theWebbBlog/node_modules/bluebird/js/release/async.js:138:12)
    at Async._drainQueues (/Users/netopwibby/Desktop/Projects/NetOperatorWibby/theWebbBlog/node_modules/bluebird/js/release/async.js:143:10)
    at Immediate.Async.drainQueues (/Users/netopwibby/Desktop/Projects/NetOperatorWibby/theWebbBlog/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:574:20)
    at tryOnImmediate (timers.js:554:5)
    at processImmediate [as _immediateCallback] (timers.js:533:5)
```

Your README says to put `{{ readingTime(page.content) }}` in `post.ejs` but as I am using Handlebars, I put it in `post.hbs`.

**Comment by ierhyna** [comment]
@NetOperatorWibby As I understand, it's not possible to call function with arguments using Handlebars, so I suspect the plugin cannot work with Handlebars.

**Comment by NetOpWibby** [comment]
Damn, that's what I expected but I was hoping I missed something. Oh well, thanks for checking this out!
